Refactor ssh-tmux a bit

diff --git a/ssh-tmux b/ssh-tmux
--- a/ssh-tmux
+++ b/ssh-tmux
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
-if [[ "${@---help}" =~ '--help' ]]; then
+
+set -e # exit on first command that fails
+
+usage() {
   >&2 cat <<HELP
-Usage: ssh-tmux chbrown@dark
+Usage: $(basename "$0") chbrown@dark
 
 For use with iTerm2 v3 with tmux integration.
 
@@ -13,7 +16,11 @@ then calls tmux with the arguments:
   -A   Attach to the named session instead of creating, if it exists
   -s 0 Specify the session name as "0"
 HELP
-  exit 1
+}
+
+if [[ "${@---help}" =~ '--help' ]]; then
+  usage
+  exit 0
 fi
 
-ssh $1 -t 'tmux -u -CC new -A -s 0'
+ssh "$1" -t 'tmux -u -CC new -A -s 0'
