Remove tgz script and implement gzip-compression switch in tjz

diff --git a/tjz b/tjz
--- a/tjz
+++ b/tjz
@@ -4,20 +4,23 @@ set -e # exit on first command that fails
 
 usage() {
   >&2 cat <<HELP
-Usage: $(basename "$0") DIRPATH[/] [-k|--keep] [-p|--prefix] [-h|--help]
+Usage: $(basename "$0") DIRPATH[/] [-g|--gzip] [-k|--keep] [-p|--prefix] [-h|--help]
 
 Tarball and bzip2-compress DIRPATH into a new file, "./DIRPATH.tar.bz2",
 then remove the original directory (using 'trash' if available; otherwise,
-moves the original directory into \$TMPDIR).
+move it into \$TMPDIR).
 
 Options:
-  -h, --help    Show this usage message
+  -g, --gzip    Use gzip instead of bzip2 compression
   -k, --keep    Keep (don't trash) the input directory
   -p, --prefix  Prefix the created tarball with the original directory's
                 date-of-birth, using the pattern "YYYYMMDD-"
+  -h, --help    Show this usage message
 HELP
 }
 
+SUFFIX=bz2
+COMPRESSOR=-j
 KEEP=false
 while [[ $# -gt 0 ]]; do
   case $1 in
@@ -25,11 +28,15 @@ while [[ $# -gt 0 ]]; do
       usage
       exit 0
       ;;
+    -g|--gzip)
+      SUFFIX=gz
+      COMPRESSOR=-z
+      ;;
     -k|--keep)
       KEEP=true
       ;;
     -p|--prefix)
-      PREFIX=%Y%m%d-
+      PREFIX_PATTERN=%Y%m%d-
       ;;
     *)
       # check that the given filepath exists and that it's a directory
@@ -39,10 +46,10 @@ while [[ $# -gt 0 ]]; do
       elif [[ ! -d $1 ]]; then
         >&2 printf '"%s" is not a directory.\n' "$1"
         exit 1
-      elif [[ -z ${original+missing} ]]; then
-        # original hasn't been set yet; set it while removing
+      elif [[ -z ${INPUT+missing} ]]; then
+        # INPUT hasn't been set yet; set it while removing
         # the trailing slash (hopefully there's only one)
-        original=${1%/}
+        INPUT=${1%/}
       else
         usage
         >&2 printf '\nToo many arguments: "%s"\n' "$1"
@@ -54,6 +61,8 @@ while [[ $# -gt 0 ]]; do
 done
 
 move() {
+  # Usage: move source-file target-file
+  #
   # if 'link' fails (e.g., due to a 'Cross-device link' error), fall back to 'mv'
   if link "$1" "$2"; then
     unlink "$1"
@@ -62,37 +71,59 @@ move() {
   fi
 }
 
-tarball=$original.tar.bz2
-# add prefix to tarball name if PREFIX is set
-if [[ ! -z ${PREFIX+missing} ]]; then
-  # %B selects the birth time of the inode (file)
-  # %SB specifies that the birth time should be converted to a string via the -t timefmt argument
-  tarball=$(stat -f '%SB' -t "$PREFIX" "$original")$tarball
-fi
+compress-dir() {
+  # Usage: compress-dir input-directory output-filepath
+  #
+  # prepare temporary file to write to
+  TMPFILE=$(mktemp -d)/$(basename "$2")
+  # COPYFILE_DISABLE=1 ignores extended attributes (xattr) on Mac OS X
+  # -c create a new archive
+  # -j compress with bzip2 / -z compress with gzip
+  # -f write to specified file
+  # -C treats the parent directory as the path context
+  # --exclude prevents files matching a pattern from being added
+  COPYFILE_DISABLE=1 tar -c $COMPRESSOR -f "$TMPFILE" \
+    -C "$(dirname "$1")" \
+    --exclude .DS_Store \
+    --exclude ._.DS_Store \
+    "$1"
+  # move into place
+  move "$TMPFILE" "$2"
+  >&2 printf 'created "%s" from contents of "%s"\n' "$2" "$1"
+}
+
+format-output() {
+  # Usage: format-output input-directory
+  PREFIX=
+  # add prefix to OUTPUT name if PREFIX_PATTERN is set
+  if [[ ! -z ${PREFIX_PATTERN+missing} ]]; then
+    # %B selects the birth time of the inode (file)
+    # %SB specifies that the birth time should be converted to a string via the -t timefmt argument
+    PREFIX=$(stat -f '%SB' -t "$PREFIX_PATTERN" "$1")
+  fi
+  printf '%s%s.tar.%s' "$PREFIX" "$1" "$SUFFIX"
+}
+
+OUTPUT=$(format-output "$INPUT")
+
 # check that the eventual output does not exist
-if [[ -e "$tarball" ]]; then
-  >&2 printf '"%s" already exists; not overwriting.\n' "$tarball"
+if [[ -e "$OUTPUT" ]]; then
+  >&2 printf '"%s" already exists; not overwriting.\n' "$OUTPUT"
   exit 1
 fi
 
-name="$(basename "$original")"
-# write to a temporary .tar.bz2 file first
-tmp_tarball=$(mktemp -d)/$name.tar.bz2
-# COPYFILE_DISABLE=1 ignores extended attributes (xattr) on Mac OS X
-# -C treats the parent directory as the path context
-COPYFILE_DISABLE=1 tar -cjf "$tmp_tarball" -C "$(dirname "$original")" \
-  --exclude='.DS_Store' --exclude='._.DS_Store' "$name"
-move "$tmp_tarball" "$tarball"
->&2 printf 'created "%s" from contents of "%s"\n' "$tarball" "$original"
+# run main procedure
+compress-dir "$INPUT" "$OUTPUT"
 
+# clean up
 if ! $KEEP; then
   # use the 'trash' command if there is one
   if command -v trash >/dev/null 2>&1; then
-    >&2 printf 'trashing original...\n'
-    trash -v "$original"
+    >&2 printf 'trashing ...'
+    trash -v "$INPUT"
   else
     >&2 printf 'moving original to temporary directory...\n'
-    # don't use move() since $original is a directory
-    mv -v "$original" "$(mktemp -d)"
+    # don't use move() since $INPUT is a directory
+    mv -v "$INPUT" "$(mktemp -d)"
   fi
 fi
