Make tjz more robust and self-descriptive

diff --git a/tjz b/tjz
--- a/tjz
+++ b/tjz
@@ -1,28 +1,42 @@
 #!/usr/bin/env bash
+if [[ "${@---help}" =~ '--help' ]]; then
+  >&2 cat <<HELP
+Usage: tjz penn-treebank-rel3/
+
+Tarball and bzip2-compress the given directory into a [basename].tar.bz2
+archive, then move the original directory into TMPDIR.
+HELP
+  exit 1
+fi
+
+move() {
+  # if 'link' fails (e.g., due to a 'Cross-device link' error), fall back to 'mv'
+  link "$1" "$2" && unlink "$1" || mv "$1" "$2"
+}
+
 set -e # exit on first command that fails
-# Use like: tjz penn-treebank-rel3/
 
-# remove trailing slash (hopefully there's at most one)
-filepath="${1%/}"
-[ ! -e "$filepath" ] && printf %s\\n "$filepath does not exist." && exit 1
+# remove trailing slash (hopefully there's only one)
+original="${1%/}"
+name="$(basename "$original")"
 
-[ -e "$filepath.tar.bz2" ] && printf %s\\n "$filepath.tar.bz2 already exists, not overwriting." && exit 1
+# check that the given filepath exists
+[ ! -e "$original" ] && >&2 printf "%s does not exist.\n" "$original" && exit 1
+# check that the eventual output does not exist
+[ -e "$original.tar.bz2" ] && >&2 printf "%s already exists, not overwriting.\n" "$original.tar.bz2" && exit 1
 
-filename="$(basename "$filepath")"
-
-# prepare to treat the parent directory as the path context
-dirpath="$(dirname "$filepath")"
-
-TMP_DIRPATH=$(mktemp -d -t tjz.XXXXXXXX)
-tmp_tar_bz2="$TMP_DIRPATH/$filename.tar.bz2"
-
+# write to a temporary .tar.bz2 file first
+tmp_tar_bz2="${TMPDIR-/tmp/}$name.tar.bz2"
 # COPYFILE_DISABLE=1 ignores extended attributes (xattr) on Mac OS X
-COPYFILE_DISABLE=1 tar -cjf "$tmp_tar_bz2" -C "$dirpath" --exclude='.DS_Store' --exclude='._.DS_Store' "$filename"
-# >&2 printf %s\\n "created $tmp_tar_bz2"
-# if link fails (say, due to a 'Cross-device link' error), fall back to mv
-link "$tmp_tar_bz2" "$filepath.tar.bz2" || mv "$tmp_tar_bz2" "$filepath.tar.bz2"
+# treat the parent directory as the path context
+COPYFILE_DISABLE=1 tar -cjf "$tmp_tar_bz2" -C "$(dirname "$original")" \
+  --exclude='.DS_Store' --exclude='._.DS_Store' "$name"
+# >&2 printf "created %s\\n" "$tmp_tar_bz2"
+move "$tmp_tar_bz2" "$original.tar.bz2"
 
-tmp_filepath="/tmp/$filename-$(date +%Y%m%dT%H%M%S)"
-mv "$filepath" "$tmp_filepath"
+# move the original to a timestamp-suffixed location in the system TMPDIR
+original_trash="${TMPDIR-/tmp/}$name-$(date +%Y%m%dT%H%M%S)"
+# don't use move since $original might be (is probably) a directory
+mv "$original" "$original_trash"
 
-printf %s\\n "created $filename.tar.bz2 and moved original to $tmp_filepath"
+>&2 printf "created %s and moved original to %s\n" "$original.tar.bz2" "$original_trash"
